grpc:
  client:
    hub-router:
      address: static://localhost:59090
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    snapshot-value-deserializer: ru.yandex.practicum.kafka.serializer.SnapshotDeserializer
    snapshot-group-id: snapshots
    hub-value-deserializer: ru.yandex.practicum.kafka.serializer.HubEventDeserializer
    hub-group-id: analyzer

topics:
  snapshots: telemetry.snapshots.v1
  hub-event: telemetry.hubs.v1

spring:
  application:
    name: analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telemetrydb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true